<?php

namespace Shortener\Web\Controls\LinkList;

use Shortener\Controls\LinkList\LinkListControl;

/**
 * Autogenerated factory for LinkList control
 *
 * @author  Hynek Nerad <iam@kennydaren.me>
 * @package Shortener\Web\Controls\LinkList
 */
interface ILinkListControlFactory
{
	/**
	 * @return LinkListControl
	 */
	public function create();
}