<?php

namespace Shortener\Web\Controls\LinkShortener;

/**
 * Autogenerated factory for Link Shortener Control
 *
 * @author  Hynek Nerad <iam@kennydaren.me>
 * @package Shortener\Web\Controls\LinkShortener
 */
interface ILinkShortenerControlFactory
{
	/** @return LinkShortenerControl */
	public function create();
}