<?php

namespace Shortener\Web\Controls\LinkGraph;

/**
 * Autogenerated factory for link graph control
 *
 * @author  Hynek Nerad <iam@kennydaren.me>
 * @package Shortener\Web\Controls\LinkGraph
 */
interface ILinkGraphControlFactory
{
	/** @return LinkGraphControl */
	public function create();
}